name: Deploy to GitHub Pages
on:
  workflow_dispatch:
jobs:
  deploy:
    uses: "odysseyprogramme/odysseyprogramme.github.io/.github/workflows/github_pages.yml@main"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "pelicanconf.py"
